# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name': '\u79d1\u5ba4\u4fe1\u606f'},
        ),
        migrations.AlterModelTable(
            name='sector',
            table='sector',
        ),
    ]
