# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170806_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name': 'ICD-10\u8bca\u65ad\u4fe1\u606f'},
        ),
        migrations.AlterModelOptions(
            name='drgs',
            options={'verbose_name': 'DRGs\u4fe1\u606f'},
        ),
        migrations.AlterModelOptions(
            name='index',
            options={'verbose_name': '\u6307\u6807\u4fe1\u606f'},
        ),
        migrations.AlterModelOptions(
            name='indexgroup',
            options={'verbose_name': '\u6307\u6807\u7ec4\u4fe1\u606f'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': '\u8017\u6750\u4fe1\u606f'},
        ),
        migrations.AlterModelOptions(
            name='medicines',
            options={'verbose_name': '\u836f\u54c1\u4fe1\u606f'},
        ),
        migrations.AlterModelOptions(
            name='operation',
            options={'verbose_name': 'ICD-9\u624b\u672f\u4fe1\u606f'},
        ),
        migrations.AlterModelOptions(
            name='servicepackage',
            options={'verbose_name': '\u670d\u52a1\u5305\u4fe1\u606f'},
        ),
        migrations.AlterModelOptions(
            name='specialhandler',
            options={'verbose_name': '\u7279\u6b8a\u573a\u666f\u4fe1\u606f'},
        ),
        migrations.AlterModelOptions(
            name='treatment',
            options={'verbose_name': '\u8bca\u7597\u4fe1\u606f'},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'verbose_name': 'DRGs\u7248\u672c\u4fe1\u606f'},
        ),
        migrations.AlterModelTable(
            name='diagnosis',
            table='diagnosis',
        ),
        migrations.AlterModelTable(
            name='drgs',
            table='drgs',
        ),
        migrations.AlterModelTable(
            name='index',
            table='index',
        ),
        migrations.AlterModelTable(
            name='indexgroup',
            table='indexgroup',
        ),
        migrations.AlterModelTable(
            name='material',
            table='material',
        ),
        migrations.AlterModelTable(
            name='medicines',
            table='medicines',
        ),
        migrations.AlterModelTable(
            name='operation',
            table='operation',
        ),
        migrations.AlterModelTable(
            name='servicepackage',
            table='servicepackage',
        ),
        migrations.AlterModelTable(
            name='specialhandler',
            table='specialhandler',
        ),
        migrations.AlterModelTable(
            name='treatment',
            table='treatment',
        ),
        migrations.AlterModelTable(
            name='version',
            table='version',
        ),
    ]
